// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpxkljdktiaealhrencw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJweGtsamRrdGlhZWFsaHJlbmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDQzNDEsImV4cCI6MjA1ODk4MDM0MX0.9bHfoWpKwgFpodOBShMf3mGQlgrlXpvey3o9YgK4mFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);